# -*- python -*-
Import("env")

import lsst.tests

tests = lsst.tests.Control(env, ignoreList=[])

for target in tests.run("*.py"):
    env.Depends(target, "../python/lsst/ip/isr/_isrLib%s" % (env["LDMODULESUFFIX"]))
