# -*- python -*-
Import('env')
	
prodName = env['eups_product']
	["../src/" + s for s in (
		"instrumentSignatureRemovalController.cc",
                "interpolateOverMaskedPixels.cc",
		"saturationCorrectionForChunkExposure.cc",
                "overscanCorrectAndTrimChunkExposure.cc",
		"biasCorrectChunkExposure.cc",
		"darkCurrentCorrectChunkExposure.cc",
		"linearizeChunkExposure.cc",
                "flatFieldCorrectChunkExposure.cc",
        #        "pupilImageCorrection.cc",
        #        "geometricDistortionCorrection.cc",
                "illuminationCorrection.cc",
        #        "maskAndCorrectAdditionalArtifacts.cc",
                "defringeChunkExposure.cc"
	#        "crosstalkCorrectChunkExposure.cc", not implemented for nightly
	#        "additionalFlatCorrection.cc" not implemented for nightly
	)],
	
env.SharedLibraryIncomplete(
	prodName,
	LIBS=[x for x in env.getlibs(prodName) if x != prodName]
)
