# -*- python -*-
Import('env')
	
prodName = env['eups_product']
	
env.SharedLibraryIncomplete(
	prodName,
	["../src/" + s for s in (
		"instrumentSignatureRemovalController.cc",
		"assembleChunkExposure.cc",
                "interpolateOverMaskedPixels.cc",
		"saturationCorrectionForChunkExposure.cc",
                "overscanCorrectChunkExposure.cc",
                "trimChunkExposure.cc",	
		"biasCorrectChunkExposure.cc",
		"darkCurrentCorrectChunkExposure.cc",
		"linearizeChunkExposure.cc",
                "flatCorrectChunkExposure.cc",
                "pupilImageCorrection.cc",
                "geometricDistortionCorrection.cc",
                "scatteredLightCorrection.cc",
                "illuminationCorrection.cc",
                "maskAdditionalArtifacts.cc",
                "defringeChunkExposure.cc",
	#        "crosstalkCorrectChunkExposure.cc", not implemented for nightly
	#        "additionalFlatCorrection.cc" not implemented for nightly
	)],
	LIBS=[x for x in env.getlibs(prodName) if x != prodName]
)
