# -*- python -*-
Import("env")
import sys
	
import lsst.tests
	
import lsst.SConsUtils as scons         # scons 1.17 supports "env.ProductDir", but for now use scons.ProductDir
dataDir = scons.ProductDir("afwData")
args = {
}
#
# Tests
#
ignoreList = [
	]
	
if not dataDir:
	sys.stderr.write("afwdata is not set up; skipping tests requiring data\n")
	ignoreList += args.keys()

tests = lsst.tests.Control(env, args=args, ignoreList=ignoreList, verbose=True)
tests.run("*.cc")
for target in tests.run("*.py"):
	env.Depends(target, "../python/lsst/ip/isr/_isrLib%s" % (env["LDMODULESUFFIX"]))
